congreso_admin:
    resource: "@CongresoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

congreso_congreso:
    resource: "@CongresoCongresoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
